/* PassFail.c Copyright(c) 2016 Jonathan D. Lettvin, All Rights Reserved. */
#ifndef C_PASSFAIL_H_
#define C_PASSFAIL_H_
/** passfail
 *
 * \class Omni
 *
 * \ingroup jlettvin
 *
 * \brief Unit test support function
 *
 * \author Jonathan D. Lettvin
 * jlettvin@gmail.com
 *
 * \version 0.0.1
 *
 * \date 2016/12/10 09:47
 *
 * license GPLv3
 *
 * \copyright Copyright(C) 2016 Jonathan D. Lettvin, All Rights Reserved"
 */

/** passfail
 *
 * \param T a 0 or 1 value (boolean) to decide reporting.
 * \param F a filename such as generated by __FILE__
 * \param L a linenumber such as generated by __LINE__
 * \param msg a string to report for either pass or fail.
 * \return nothing.
 *
 * The PASSFAIL macro simplifies use in unit tests by
 * eliminating the need for explicit filename/linenumber identification.
 */
void passfail(const int T, const char* F, const unsigned L, const char* msg);
#define PASSFAIL(T, msg) passfail(T, __FILE__, __LINE__, msg)
#endif  // C_PASSFAIL_H_
